"""LLM provider abstraction (SPEC section 7 / 14).

Business code depends ONLY on the `LLMProvider` interface and
`get_llm_provider()`. Switching between qwen / openai / claude is a
config change, not a code change.

The `local` provider needs no API key: it composes an extractive,
source-grounded answer directly from the retrieved context. This keeps
`/chat` working offline and makes the RAG plumbing testable without
spending tokens.
"""

from __future__ import annotations

from abc import ABC, abstractmethod

import httpx

from app.core.config import Settings, get_settings
from app.core.logging import get_logger

logger = get_logger(__name__)


class LLMProvider(ABC):
    @abstractmethod
    def complete(self, *, system: str, user: str) -> str:
        """Return the model's text completion for a system+user prompt."""


class LocalLLMProvider(LLMProvider):
    """Offline fallback: extractive answer assembled from the prompt context.

    The prompt assembled by rag/prompt.py contains a CONTEXT block and the
    user QUESTION. We surface the most relevant context verbatim so the
    answer is always grounded in retrieved sources rather than invented.
    """

    def complete(self, *, system: str, user: str) -> str:
        context = _extract_block(user, "CONTEXT")
        question = _extract_block(user, "QUESTION") or user
        if not context.strip():
            return (
                "Answer:\nI could not find supporting information in the "
                "ingested ONE Record knowledge base for this question.\n\n"
                "Implementation note:\nRun `/ingest` first, or rephrase the "
                "question around a ONE Record concept (e.g. Piece, Shipment, "
                "LogisticsObject)."
            )
        # Take the first 1-2 context snippets as the grounded answer body.
        snippets = [s.strip() for s in context.split("\n---\n") if s.strip()]
        body = "\n\n".join(snippets[:2])
        return (
            f"Answer:\n{body}\n\n"
            "Implementation note:\nThis answer is generated by the local "
            "(offline) provider and is extracted directly from the retrieved "
            "ONE Record sources. Configure LLM_PROVIDER + LLM_API_KEY for "
            "synthesized, conversational answers.\n\n"
            f"(Question: {question.strip()})"
        )


class OpenAICompatLLMProvider(LLMProvider):
    """Chat-completions client for OpenAI and Qwen (DashScope compat mode)."""

    def __init__(self, *, model: str, api_key: str, base_url: str) -> None:
        self.model = model
        self.api_key = api_key
        self.base_url = base_url.rstrip("/")

    def complete(self, *, system: str, user: str) -> str:
        resp = httpx.post(
            f"{self.base_url}/chat/completions",
            headers={"Authorization": f"Bearer {self.api_key}"},
            json={
                "model": self.model,
                "messages": [
                    {"role": "system", "content": system},
                    {"role": "user", "content": user},
                ],
                "temperature": 0.2,
            },
            timeout=120,
        )
        resp.raise_for_status()
        return resp.json()["choices"][0]["message"]["content"]


class ClaudeLLMProvider(LLMProvider):
    """Anthropic Messages API client."""

    def __init__(self, *, model: str, api_key: str, base_url: str) -> None:
        self.model = model
        self.api_key = api_key
        self.base_url = (base_url or "https://api.anthropic.com").rstrip("/")

    def complete(self, *, system: str, user: str) -> str:
        resp = httpx.post(
            f"{self.base_url}/v1/messages",
            headers={
                "x-api-key": self.api_key,
                "anthropic-version": "2023-06-01",
            },
            json={
                "model": self.model,
                "max_tokens": 1024,
                "system": system,
                "messages": [{"role": "user", "content": user}],
            },
            timeout=120,
        )
        resp.raise_for_status()
        return resp.json()["content"][0]["text"]


_LLM_BASE_URLS = {
    "openai": "https://api.openai.com/v1",
    "qwen": "https://dashscope.aliyuncs.com/compatible-mode/v1",
}


def build_llm_provider(settings: Settings) -> LLMProvider:
    provider = settings.llm_provider.lower()
    if provider == "local":
        return LocalLLMProvider()

    if not settings.llm_api_key:
        logger.warning(
            "LLM_PROVIDER=%s but LLM_API_KEY is empty; falling back to local provider.",
            provider,
        )
        return LocalLLMProvider()

    if provider == "claude":
        return ClaudeLLMProvider(
            model=settings.llm_model,
            api_key=settings.llm_api_key,
            base_url=settings.llm_base_url,
        )

    base_url = settings.llm_base_url or _LLM_BASE_URLS.get(provider, "")
    if not base_url:
        logger.warning("Unknown LLM provider %r; falling back to local.", provider)
        return LocalLLMProvider()

    return OpenAICompatLLMProvider(
        model=settings.llm_model,
        api_key=settings.llm_api_key,
        base_url=base_url,
    )


def _extract_block(text: str, label: str) -> str:
    """Pull the text of a '<LABEL>:' ... block produced by prompt.py."""
    marker = f"{label}:"
    start = text.find(marker)
    if start == -1:
        return ""
    start += len(marker)
    # next block is another ALLCAPS label followed by ':'
    rest = text[start:]
    end = len(rest)
    for other in ("CONTEXT:", "QUESTION:"):
        if other == f"{label}:":
            continue
        i = rest.find(other)
        if i != -1:
            end = min(end, i)
    return rest[:end].strip()


_provider: LLMProvider | None = None


def get_llm_provider() -> LLMProvider:
    global _provider
    if _provider is None:
        _provider = build_llm_provider(get_settings())
    return _provider
